# Generated by Django 4.0.4 on 2022-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0010_remove_earthquake_country_remove_earthquake_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake',
            old_name='año1',
            new_name='taño1',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='año2',
            new_name='taño2',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='año3',
            new_name='taño3',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='categoria',
            new_name='tcategoria',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='cifra1',
            new_name='tcifra1',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='cifra2',
            new_name='tcifra2',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='cifra3',
            new_name='tcifra3',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='spread_area',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='wave_height',
        ),
        migrations.AddField(
            model_name='tsunami',
            name='taño1',
            field=models.CharField(default='2019', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='taño2',
            field=models.CharField(default='2020', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='taño3',
            field=models.CharField(default='2021', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='tcategoria',
            field=models.CharField(default='Homicidio', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='tcifra1',
            field=models.CharField(default='383', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='tcifra2',
            field=models.CharField(default='427', max_length=50),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='tcifra3',
            field=models.CharField(default='462', max_length=50),
        ),
    ]
