# Generated by Django 4.0.4 on 2022-11-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0012_remove_volcaniceruption_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake',
            old_name='taño1',
            new_name='eaño1',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='taño2',
            new_name='eaño2',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='taño3',
            new_name='eaño3',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='tcategoria',
            new_name='ecategoria',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='tcifra1',
            new_name='ecifra1',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='tcifra2',
            new_name='ecifra2',
        ),
        migrations.RenameField(
            model_name='earthquake',
            old_name='tcifra3',
            new_name='ecifra3',
        ),
    ]
