# Generated by Django 4.0.4 on 2022-11-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0013_rename_taño1_earthquake_eaño1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsunami',
            name='tcifra1',
            field=models.CharField(default='190', max_length=50),
        ),
    ]
