# Generated by Django 4.0.4 on 2022-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0014_alter_tsunami_tcifra1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsunami',
            name='tcifra1',
            field=models.CharField(default='197', max_length=50),
        ),
    ]
