# Generated by Django 4.0.4 on 2022-11-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0015_alter_tsunami_tcifra1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthquake',
            name='ecategoria',
        ),
        migrations.RemoveField(
            model_name='tsunami',
            name='tcategoria',
        ),
        migrations.RemoveField(
            model_name='volcaniceruption',
            name='categoria',
        ),
    ]
