# Generated by Django 4.0.4 on 2022-11-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0016_remove_earthquake_ecategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsunami',
            old_name='taño1',
            new_name='tsaño1',
        ),
        migrations.RenameField(
            model_name='tsunami',
            old_name='taño2',
            new_name='tsaño2',
        ),
        migrations.RenameField(
            model_name='tsunami',
            old_name='taño3',
            new_name='tsaño3',
        ),
        migrations.RenameField(
            model_name='tsunami',
            old_name='tcifra1',
            new_name='tscifra1',
        ),
        migrations.RenameField(
            model_name='tsunami',
            old_name='tcifra2',
            new_name='tscifra2',
        ),
        migrations.RenameField(
            model_name='tsunami',
            old_name='tcifra3',
            new_name='tscifra3',
        ),
    ]
